<?php

return [

    // frontend
    'guest'      => [
        'admin/index'       => '*',
        'index/index'       => '*',
        'index/error'       => '*',
        'page/index'        => '*',
        'webform/index'     => '*',
        'employee/index'    => '*',
        'publication/index' => '*',
        'products/index'    => '*',
        'tours/index'       => '*',
        'seo/index'         => '*',
        'seo/rss'           => '*',
        'portfolio/index'   => '*',
        'search/index'      => '*',
        'partner/index'     => '*',
        'faq/index'         => '*',
    ], 
    'member'     => [
        'index/index' => '*',
    ],
    // backend
    'journalist' => [
        'publication/admin'  => [
            'index',
            'add',
            'edit',
        ],
        'page/admin'         => [
            'index',
            'add',
            'edit',
        ],        
    ],
    'editor'     => [
        'publication/admin'  => '*',
        'publication/type'   => '*',        
        'cms/translate'      => '*',
        'widget/admin'       => '*',
        'file-manager/index' => '*',
        'page/admin'         => '*',
        'tree/admin'         => '*',
        'menu/admin'         => '*',
        'slider/admin'       => '*',
        'employee/admin'     => '*',
        'reviews/admin'      => '*',
        'portfolio/admin'    => '*',
        'portfolio/category' => '*',
        'products/admin'     => '*',
        'products/category'  => '*',
        'tours/admin'        => '*', 
        'tours/category'     => '*',
        'tours/country'      => '*',   
    ],
    'admin'      => [
        'admin/admin-user'   => '*',
        'cms/configuration'  => '*',
        'cms/settings'       => '*',        
        'cms/translate'      => '*',
        'cms/language'       => '*',
        'cms/javascript'     => '*',
        'widget/admin'       => '*',
        'file-manager/index' => '*',
        'page/admin'         => '*',
        'publication/admin'  => '*',
        'publication/type'   => '*',
        'seo/robots'         => '*',
        'menu/admin'         => '*',
        'slider/admin'       => '*',
        'employee/admin'     => '*',
        'reviews/admin'      => '*',
        'portfolio/admin'    => '*',
        'portfolio/category' => '*',
        'products/admin'     => '*',
        'products/category'  => '*', 
        'tours/admin'        => '*', 
        'tours/category'     => '*', 
        'tours/country'      => '*', 
        'partner/admin'      => '*',
        'faq/admin'          => '*',
    ],
];